function [ L, R ] = quat2mat( q )
%QUAT2MAT compute left and right matrix from a quaternion

qx = q(1);
qy = q(2);
qz = q(3);
qw = q(4);

R = [ ...
    qw qz -qy qx; ...
    -qz qw qx qy; ...
    qy -qx qw qz; ...
    -qx -qy -qz qw];

L = [ ...
    qw -qz qy qx; ...
    qz qw -qx qy; ...
    -qy qx qw qz; ...
    -qx -qy -qz qw];

end

