function [vec_cost, mat_Jacobian, cellmat_Hessian] = CostJacobHess_Spatio(this, vec_mu_x, vec_mu_y)
%COSTJACOBHESS_SPATIO Summary of this function goes here
%   Detailed explanation goes here

%% compute cost function
vec_cost = Cost_Spatio(this, vec_mu_x, vec_mu_y);

%% compute Jacobian and Hessian
% if nargout > 1
%     
%     %% compute Jacobian numerically
%     delta = 1e-3;
%     
%     num_x = numel(vec_mu_x);
%     num_y = numel(vec_mu_y);
%     num_c = numel(vec_cost);
%     
%     cellmat_cost_dx = cell(num_x, 2);
%     cellmat_cost_dy = cell(num_y, 2);
%     mat_Jacobian_x = zeros(num_c, num_x);
%     mat_Jacobian_y = zeros(num_c, num_y);
%     
%     for i = 1:num_x
%         vec_mu_dx_1 = vec_mu_x;
%         vec_mu_dx_1(i) = vec_mu_dx_1(i) + delta;
%         vec_mu_dx_2 = vec_mu_x;
%         vec_mu_dx_2(i) = vec_mu_dx_2(i) - delta;
%         
%         vec_cost_1 = Cost_Spatio(this, vec_mu_dx_1, vec_mu_y);
%         vec_cost_2 = Cost_Spatio(this, vec_mu_dx_2, vec_mu_y);
%         cellmat_cost_dx(i,:) = {vec_cost_1 vec_cost_2};
%         
%         mat_Jacobian_x(:,i) = (vec_cost_1-vec_cost_2)/(2*delta);
%     end
%     
%     for i = 1:num_y
%         vec_mu_dy_1 = vec_mu_y;
%         vec_mu_dy_1(i) = vec_mu_dy_1(i) + delta;
%         vec_mu_dy_2 = vec_mu_y;
%         vec_mu_dy_2(i) = vec_mu_dy_2(i) - delta;
%         
%         vec_cost_1 = Cost_Spatio(this, vec_mu_x, vec_mu_dy_1);
%         vec_cost_2 = Cost_Spatio(this, vec_mu_x, vec_mu_dy_2);
%         cellmat_cost_dy(i,:) = {vec_cost_1 vec_cost_2};
%         
%         mat_Jacobian_y(:,i) = (vec_cost_1-vec_cost_2)/(2*delta);
%     end
%     
%     cellmat_cost_d = [cellmat_cost_dx; cellmat_cost_dy];
%     mat_Jacobian = [mat_Jacobian_x mat_Jacobian_y];
%     
%     %% compute Hessian numerically
%     cellmat_Hessian = cell(num_c, 1);
%     for i = 1:num_c
%         cellmat_Hessian{i} = zeros(num_x+num_y, num_x+num_y);
%     end
%     
%     %     mat_Hessian_bool = eye(num_x+num_y, num_x+num_y);
%     %
%     %     vecrow_rvec_b_c = [1;2;3];
%     %     vecrow_tvec_b_c = [4;5];
%     %     vecrow_k_odo_lin = 6;
%     %     vecrow_k_odo_rot = 7;
%     %     vecrow_tvec_b1_b2 = [8;9];
%     %     vecrow_rvec_b1_b2 = 10;
%     %     vecrow_tvec_c1_m = [11;12;13];
%     %     vecrow_tvec_c2_m = [14;15;16];
%     %
%     %     vecrow_1 = [vecrow_rvec_b_c;vecrow_tvec_c1_m];
%     %     vecrow_2 = [vecrow_rvec_b_c; vecrow_k_odo_rot; vecrow_rvec_b1_b2; vecrow_tvec_c2_m];
%     %     vecrow_3 = [vecrow_k_odo_rot; vecrow_rvec_b1_b2; vecrow_tvec_b1_b2];
%     %     vecrow_4 = [vecrow_k_odo_lin; vecrow_tvec_b1_b2];
%     %
%     %     mat_Hessian_bool(vecrow_1, vecrow_1) = ones(numel(vecrow_1));
%     %     mat_Hessian_bool(vecrow_2, vecrow_2) = ones(numel(vecrow_2));
%     %     mat_Hessian_bool(vecrow_3, vecrow_3) = ones(numel(vecrow_3));
%     %     mat_Hessian_bool(vecrow_4, vecrow_4) = ones(numel(vecrow_4));
%     
%     mat_Hessian_bool = ones(num_x+num_y, num_x+num_y);
%     
%     cellmat_cost_dd = cell(num_x+num_y, num_x+num_y);
%     
%     vec_mu_xy = [vec_mu_x; vec_mu_y];
%     
%     % off-diagonal elements
%     for i = 1:(num_x+num_y-1)
%         for j = i+1:(num_x+num_y)
%             if mat_Hessian_bool(i,j) == 1
%                 
%                 vec_mu_xy_d = vec_mu_xy;
%                 vec_mu_xy_d(i) = vec_mu_xy_d(i)+delta;
%                 vec_mu_xy_d(j) = vec_mu_xy_d(j)+delta;
%                 
%                 vec_mu_x_d = vec_mu_xy_d(1:num_x);
%                 vec_mu_y_d = vec_mu_xy_d(num_x+1:num_x+num_y);
%                 
%                 vec_cost_d = Cost_Spatio(this, vec_mu_x_d, vec_mu_y_d);
%                 cellmat_cost_dd{i,j} = vec_cost_d;
%                 cellmat_cost_dd{j,i} = vec_cost_d;
%                 
%                 for k = 1:num_c
%                     
%                     cellmat_Hessian{k}(i,j) = ...
%                         (cellmat_cost_dd{i,j}(k)+vec_cost(k)-cellmat_cost_d{i,1}(k)-cellmat_cost_d{j,1}(k))/(delta*delta);
%                     cellmat_Hessian{k}(j,i) = cellmat_Hessian{k}(i,j);
%                     
%                 end
%             end
%         end
%     end
%     
%     % diagonal elements
%     for i = 1:(num_x+num_y)
%         if mat_Hessian_bool(i,i) == 1
%             for k = 1:num_c
%                 cellmat_Hessian{k}(i,i) = ...
%                     (cellmat_cost_d{i,1}(k)+cellmat_cost_d{i,2}(k)-2*vec_cost(k))/(delta*delta);
%             end
%         end
%     end
%     
% end

%% old way ...

qx_c_b = vec_mu_x(1); qy_c_b = vec_mu_x(2); qz_c_b = vec_mu_x(3); qw_c_b = vec_mu_x(4);
x_c_b = vec_mu_x(5); y_c_b = vec_mu_x(6);

x_b2_b1 = vec_mu_y(1); y_b2_b1 = vec_mu_y(2); theta_b2_b1 = vec_mu_y(3);
x_m_c1 = vec_mu_y(4); y_m_c1 = vec_mu_y(5); z_m_c1 = vec_mu_y(6);
x_m_c2 = vec_mu_y(7); y_m_c2 = vec_mu_y(8); z_m_c2 = vec_mu_y(9);

%% for z1
% Hessian
H1 = ...
[                                                                                                                                 2*x_m_c1 - 2*x_m_c2*cos(theta_b2_b1) + 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                                                                                                                                                             2*z_m_c2*cos(theta_b2_b1) - 2*z_m_c1,                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) - 2*x_m_c2*sin(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                   y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)),  2*qx_c_b, 2*qw_c_b, -2*qz_c_b,                                                             - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                               2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1),                                                                                     2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1);...
                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                                                                                                                                 2*x_m_c1 - 2*x_m_c2*cos(theta_b2_b1) - 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) + 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                                             2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                   x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)),  2*qy_c_b, 2*qz_c_b,  2*qw_c_b,                                                               2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                             - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                                     2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1);...
                                                                                                                                                             2*z_m_c2*cos(theta_b2_b1) - 2*z_m_c1,                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) + 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                 2*x_m_c2*cos(theta_b2_b1) - 2*x_m_c1 + 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                   x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)), -2*qz_c_b, 2*qy_c_b, -2*qx_c_b,                                                               2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1),                                                               2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                                                     2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1);...
                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) - 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                                             2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                                                                                                                                 2*x_m_c2*cos(theta_b2_b1) - 2*x_m_c1 - 2*y_m_c2*sin(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                   z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), -2*qw_c_b, 2*qx_c_b,  2*qy_c_b,                                                               2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                                                             - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                                                     2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1);...
                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                   sin(theta_b2_b1),         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                   cos(theta_b2_b1),         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
 y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)), x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)), z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), sin(theta_b2_b1), cos(theta_b2_b1), 0, 0, x_c_b*cos(theta_b2_b1) - y_c_b*sin(theta_b2_b1) - z_m_c2*(2*qx_c_b*qz_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qz_c_b*sin(theta_b2_b1) + 2*qx_c_b*qy_c_b*sin(theta_b2_b1)) + x_m_c2*(sin(theta_b2_b1)*(2*qw_c_b*qx_c_b - 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2)) + y_m_c2*(cos(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) + sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2)),         0,        0,         0, - 2*cos(theta_b2_b1)*(qw_c_b*qx_c_b - qy_c_b*qz_c_b) - sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2), sin(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2), 2*qw_c_b*qz_c_b*cos(theta_b2_b1) + 2*qx_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qy_c_b*sin(theta_b2_b1) - 2*qx_c_b*qz_c_b*sin(theta_b2_b1);...
                                                                                                                                                                                         2*qx_c_b,                                                                                                                                                                                         2*qy_c_b,                                                                                                                                                                                        -2*qz_c_b,                                                                                                                                                                                        -2*qw_c_b,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                                                                         2*qw_c_b,                                                                                                                                                                                         2*qz_c_b,                                                                                                                                                                                         2*qy_c_b,                                                                                                                                                                                         2*qx_c_b,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                                                                        -2*qz_c_b,                                                                                                                                                                                         2*qw_c_b,                                                                                                                                                                                        -2*qx_c_b,                                                                                                                                                                                         2*qy_c_b,                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                          - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                                                                                                            2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                                                                                                            2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1),                                                                                                                                            2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                - 2*cos(theta_b2_b1)*(qw_c_b*qx_c_b - qy_c_b*qz_c_b) - sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2),         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                            2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1),                                                                                                                                          - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                                                                                            2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                                                                                                          - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                sin(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2),         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0;...
                                                                                                                                            2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1),                                                                                                                                            2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1),                                                                                                                                            2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1),                                                                                                                                            2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                          2*qw_c_b*qz_c_b*cos(theta_b2_b1) + 2*qx_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qy_c_b*sin(theta_b2_b1) - 2*qx_c_b*qz_c_b*sin(theta_b2_b1),         0,        0,         0,                                                                                                                   0,                                                                                                                   0,                                                                                                                                         0];

% Jacobian
J1 = [ 2*qx_c_b*x_m_c1 + 2*qw_c_b*y_m_c1 - 2*qz_c_b*z_m_c1 - x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)), 2*qy_c_b*x_m_c1 + 2*qz_c_b*y_m_c1 + 2*qw_c_b*z_m_c1 - x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)), 2*qy_c_b*y_m_c1 - 2*qz_c_b*x_m_c1 - 2*qx_c_b*z_m_c1 + x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), 2*qx_c_b*y_m_c1 - 2*qw_c_b*x_m_c1 + 2*qy_c_b*z_m_c1 + x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)), 1 - cos(theta_b2_b1), sin(theta_b2_b1), -1, 0, y_c_b*cos(theta_b2_b1) + x_c_b*sin(theta_b2_b1) + z_m_c2*(2*qw_c_b*qz_c_b*cos(theta_b2_b1) + 2*qx_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qy_c_b*sin(theta_b2_b1) - 2*qx_c_b*qz_c_b*sin(theta_b2_b1)) - x_m_c2*(cos(theta_b2_b1)*(2*qw_c_b*qx_c_b - 2*qy_c_b*qz_c_b) + sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2)) + y_m_c2*(sin(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2)), - qw_c_b^2 + qx_c_b^2 + qy_c_b^2 - qz_c_b^2, 2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b, 2*qw_c_b*qy_c_b - 2*qx_c_b*qz_c_b, cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2) - 2*sin(theta_b2_b1)*(qw_c_b*qx_c_b - qy_c_b*qz_c_b), - cos(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2), 2*qx_c_b*qz_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qz_c_b*sin(theta_b2_b1) + 2*qx_c_b*qy_c_b*sin(theta_b2_b1)];

%% for z2
% Hessian
H2 = ...
[                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) - 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                                               2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                                                                                                                                 2*x_m_c2*cos(theta_b2_b1) - 2*x_m_c1 - 2*y_m_c2*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                   z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), -2*qw_c_b,  2*qx_c_b, 2*qy_c_b,                                                             2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                                                               - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                                                     2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1);...
                                                                                                                                                             2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                                                                                                                                   2*y_m_c2*cos(theta_b2_b1) - 2*y_m_c1 - 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                 2*x_m_c1 - 2*x_m_c2*cos(theta_b2_b1) - 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                                                       -2*z_m_c2*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                 - x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)),  2*qz_c_b, -2*qy_c_b, 2*qx_c_b,                                                           - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                 2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1),                                                                                   - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1);...
                                                                                                                                                                        2*z_m_c2*sin(theta_b2_b1),                                                                                                                                   2*x_m_c1 - 2*x_m_c2*cos(theta_b2_b1) - 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                 2*y_m_c1 - 2*y_m_c2*cos(theta_b2_b1) + 2*x_m_c2*sin(theta_b2_b1),                                                                                                                                                             2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                   x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)),  2*qy_c_b,  2*qz_c_b, 2*qw_c_b,                                                             2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                               - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                                     2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1);...
                                                                                                                                 2*x_m_c2*cos(theta_b2_b1) - 2*x_m_c1 - 2*y_m_c2*sin(theta_b2_b1),                                                                                                                                                                         -2*z_m_c2*sin(theta_b2_b1),                                                                                                                                                             2*z_m_c1 - 2*z_m_c2*cos(theta_b2_b1),                                                                                                                                 2*y_m_c2*cos(theta_b2_b1) - 2*y_m_c1 + 2*x_m_c2*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                   x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)), -2*qx_c_b, -2*qw_c_b, 2*qz_c_b,                                                             2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1),                                                                 2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                                                                                   - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1);...
                                                                                                                                                                                                0,                                                                                                                                                                                                  0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                  -cos(theta_b2_b1),         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                  0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                   sin(theta_b2_b1),         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                  0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                                                                                0,                                                                                                                                                                                                  0,                                                                                                                                                                                                0,                                                                                                                                                                                                0,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
 z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), - x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)), x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) + z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)), -cos(theta_b2_b1), sin(theta_b2_b1), 0, 0, y_c_b*cos(theta_b2_b1) + x_c_b*sin(theta_b2_b1) + z_m_c2*(2*qw_c_b*qz_c_b*cos(theta_b2_b1) + 2*qx_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qy_c_b*sin(theta_b2_b1) - 2*qx_c_b*qz_c_b*sin(theta_b2_b1)) - x_m_c2*(cos(theta_b2_b1)*(2*qw_c_b*qx_c_b - 2*qy_c_b*qz_c_b) + sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2)) + y_m_c2*(sin(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2)),         0,         0,        0, cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2) - 2*sin(theta_b2_b1)*(qw_c_b*qx_c_b - qy_c_b*qz_c_b), - cos(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2), 2*qx_c_b*qz_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qz_c_b*sin(theta_b2_b1) + 2*qx_c_b*qy_c_b*sin(theta_b2_b1);...
                                                                                                                                                                                        -2*qw_c_b,                                                                                                                                                                                           2*qz_c_b,                                                                                                                                                                                         2*qy_c_b,                                                                                                                                                                                        -2*qx_c_b,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                                                                         2*qx_c_b,                                                                                                                                                                                          -2*qy_c_b,                                                                                                                                                                                         2*qz_c_b,                                                                                                                                                                                        -2*qw_c_b,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                                                                         2*qy_c_b,                                                                                                                                                                                           2*qx_c_b,                                                                                                                                                                                         2*qw_c_b,                                                                                                                                                                                         2*qz_c_b,                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                            2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                                                                                                                                            - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                                                                                            2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                                                                                                            2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                                  cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2) - 2*sin(theta_b2_b1)*(qw_c_b*qx_c_b - qy_c_b*qz_c_b),         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                          - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                                                                                                              2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1),                                                                                                                                          - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                                                                                                                                            2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                                              - cos(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) - sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2),         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0;...
                                                                                                                                            2*qz_c_b*sin(theta_b2_b1) - 2*qy_c_b*cos(theta_b2_b1),                                                                                                                                            - 2*qx_c_b*cos(theta_b2_b1) - 2*qw_c_b*sin(theta_b2_b1),                                                                                                                                            2*qx_c_b*sin(theta_b2_b1) - 2*qw_c_b*cos(theta_b2_b1),                                                                                                                                          - 2*qz_c_b*cos(theta_b2_b1) - 2*qy_c_b*sin(theta_b2_b1),                 0,                0, 0, 0,                                                                                                                                                                                                                                                                                                                          2*qx_c_b*qz_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qz_c_b*sin(theta_b2_b1) + 2*qx_c_b*qy_c_b*sin(theta_b2_b1),         0,         0,        0,                                                                                                                 0,                                                                                                                     0,                                                                                                                                         0];

% Jacobian
J2 = [ 2*qx_c_b*y_m_c1 - 2*qw_c_b*x_m_c1 + 2*qy_c_b*z_m_c1 + x_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)), 2*qz_c_b*x_m_c1 - 2*qy_c_b*y_m_c1 + 2*qx_c_b*z_m_c1 - x_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) + y_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)), 2*qy_c_b*x_m_c1 + 2*qz_c_b*y_m_c1 + 2*qw_c_b*z_m_c1 - x_m_c2*(2*qy_c_b*cos(theta_b2_b1) - 2*qz_c_b*sin(theta_b2_b1)) - y_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)), 2*qz_c_b*z_m_c1 - 2*qw_c_b*y_m_c1 - 2*qx_c_b*x_m_c1 + x_m_c2*(2*qx_c_b*cos(theta_b2_b1) + 2*qw_c_b*sin(theta_b2_b1)) + y_m_c2*(2*qw_c_b*cos(theta_b2_b1) - 2*qx_c_b*sin(theta_b2_b1)) - z_m_c2*(2*qz_c_b*cos(theta_b2_b1) + 2*qy_c_b*sin(theta_b2_b1)), -sin(theta_b2_b1), 1 - cos(theta_b2_b1), 0, -1, y_c_b*sin(theta_b2_b1) - x_c_b*cos(theta_b2_b1) + z_m_c2*(2*qx_c_b*qz_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*cos(theta_b2_b1) + 2*qw_c_b*qz_c_b*sin(theta_b2_b1) + 2*qx_c_b*qy_c_b*sin(theta_b2_b1)) - x_m_c2*(sin(theta_b2_b1)*(2*qw_c_b*qx_c_b - 2*qy_c_b*qz_c_b) - cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2)) - y_m_c2*(cos(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b) + sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2)), 2*qy_c_b*qz_c_b - 2*qw_c_b*qx_c_b, - qw_c_b^2 + qx_c_b^2 - qy_c_b^2 + qz_c_b^2, 2*qw_c_b*qz_c_b + 2*qx_c_b*qy_c_b, cos(theta_b2_b1)*(2*qw_c_b*qx_c_b - 2*qy_c_b*qz_c_b) + sin(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 - qy_c_b^2 + qz_c_b^2), cos(theta_b2_b1)*(qw_c_b^2 - qx_c_b^2 + qy_c_b^2 - qz_c_b^2) - sin(theta_b2_b1)*(2*qw_c_b*qx_c_b + 2*qy_c_b*qz_c_b), 2*qx_c_b*qz_c_b*sin(theta_b2_b1) - 2*qx_c_b*qy_c_b*cos(theta_b2_b1) - 2*qw_c_b*qy_c_b*sin(theta_b2_b1) - 2*qw_c_b*qz_c_b*cos(theta_b2_b1)];

%% for z3
% Hessian
H3 = ...
[ 2*z_m_c1 - 2*z_m_c2, 2*y_m_c2 - 2*y_m_c1, 2*x_m_c1 - 2*x_m_c2,                   0, 0, 0, 0, 0, 0, 2*qz_c_b, -2*qy_c_b,  2*qx_c_b, -2*qz_c_b,  2*qy_c_b, -2*qx_c_b;...
 2*y_m_c2 - 2*y_m_c1, 2*z_m_c2 - 2*z_m_c1,                   0, 2*x_m_c1 - 2*x_m_c2, 0, 0, 0, 0, 0, 2*qw_c_b, -2*qx_c_b, -2*qy_c_b, -2*qw_c_b,  2*qx_c_b,  2*qy_c_b;...
 2*x_m_c1 - 2*x_m_c2,                   0, 2*z_m_c2 - 2*z_m_c1, 2*y_m_c1 - 2*y_m_c2, 0, 0, 0, 0, 0, 2*qx_c_b,  2*qw_c_b, -2*qz_c_b, -2*qx_c_b, -2*qw_c_b,  2*qz_c_b;...
                   0, 2*x_m_c1 - 2*x_m_c2, 2*y_m_c1 - 2*y_m_c2, 2*z_m_c1 - 2*z_m_c2, 0, 0, 0, 0, 0, 2*qy_c_b,  2*qz_c_b,  2*qw_c_b, -2*qy_c_b, -2*qz_c_b, -2*qw_c_b;...
                   0,                   0,                   0,                   0, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
                   0,                   0,                   0,                   0, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
                   0,                   0,                   0,                   0, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
                   0,                   0,                   0,                   0, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
                   0,                   0,                   0,                   0, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
            2*qz_c_b,            2*qw_c_b,            2*qx_c_b,            2*qy_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
           -2*qy_c_b,           -2*qx_c_b,            2*qw_c_b,            2*qz_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
            2*qx_c_b,           -2*qy_c_b,           -2*qz_c_b,            2*qw_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
           -2*qz_c_b,           -2*qw_c_b,           -2*qx_c_b,           -2*qy_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
            2*qy_c_b,            2*qx_c_b,           -2*qw_c_b,           -2*qz_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0;...
           -2*qx_c_b,            2*qy_c_b,            2*qz_c_b,           -2*qw_c_b, 0, 0, 0, 0, 0,        0,         0,         0,         0,         0,         0];
    
% Jacobian
J3 = [ 2*qz_c_b*x_m_c1 - 2*qz_c_b*x_m_c2 - 2*qy_c_b*y_m_c1 + 2*qy_c_b*y_m_c2 + 2*qx_c_b*z_m_c1 - 2*qx_c_b*z_m_c2, 2*qw_c_b*x_m_c1 - 2*qw_c_b*x_m_c2 - 2*qx_c_b*y_m_c1 + 2*qx_c_b*y_m_c2 - 2*qy_c_b*z_m_c1 + 2*qy_c_b*z_m_c2, 2*qx_c_b*x_m_c1 - 2*qx_c_b*x_m_c2 + 2*qw_c_b*y_m_c1 - 2*qw_c_b*y_m_c2 - 2*qz_c_b*z_m_c1 + 2*qz_c_b*z_m_c2, 2*qy_c_b*x_m_c1 - 2*qy_c_b*x_m_c2 + 2*qz_c_b*y_m_c1 - 2*qz_c_b*y_m_c2 + 2*qw_c_b*z_m_c1 - 2*qw_c_b*z_m_c2, 0, 0, 0, 0, 0, 2*qw_c_b*qy_c_b + 2*qx_c_b*qz_c_b, 2*qw_c_b*qz_c_b - 2*qx_c_b*qy_c_b, qw_c_b^2 + qx_c_b^2 - qy_c_b^2 - qz_c_b^2, - 2*qw_c_b*qy_c_b - 2*qx_c_b*qz_c_b, 2*qx_c_b*qy_c_b - 2*qw_c_b*qz_c_b, - qw_c_b^2 - qx_c_b^2 + qy_c_b^2 + qz_c_b^2];

%% for z4
% Hessian
H4 = zeros(15,15);
H4(1:4,1:4) = 2*eye(4);
J4 = zeros(1,15);
J4(1,1:4) = [ 2*qx_c_b, 2*qy_c_b, 2*qz_c_b, 2*qw_c_b ];

%% combine z1:z4
mat_Jacobian = [J1; J2; J3; J4];
cellmat_Hessian{1} = H1;
cellmat_Hessian{2} = H2;
cellmat_Hessian{3} = H3;
cellmat_Hessian{4} = H4;

% dH1 = cellmat_Hessian{1} - cellmat_Hessian_old{1};
% dH2 = cellmat_Hessian{2} - cellmat_Hessian_old{2};
% dH3 = cellmat_Hessian{3} - cellmat_Hessian_old{3};
% dH4 = cellmat_Hessian{4} - cellmat_Hessian_old{4};
% 
% r1 = max(max(dH1./norm(H1)));
% r2 = max(max(dH2./norm(H2)));
% r3 = max(max(dH3./norm(H3)));
% r4 = max(max(dH4./norm(H4)));
% 
% if max([r1;r2;r3;r4] > 0.01)
%     debug = 1;
% end

end

